name: update_available_android
description: Android platform implementation of update_available
version: 2.2.1
repository: https://github.com/mateusfccp/update_available/tree/master/update_available_android

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  update_available_platform_interface: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: update_available
    platforms:
      android:
        package: me.mateusfccp.update_available_android
        pluginClass: UpdateAvailableAndroidPlugin
        dartPluginClass: UpdateAvailableAndroidPlugin
