name: update_available_android
description: Android platform implementation of update_available
version: 3.0.0-dev.2
repository: https://github.com/mateusfccp/update_available/tree/master/update_available_android

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  update_available_platform_interface: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  plugin:
    implements: update_available
    platforms:
      android:
        package: me.mateusfccp.update_available_android
        pluginClass: UpdateAvailableAndroidPlugin
        dartPluginClass: UpdateAvailableAndroidPlugin
