name: update_available_platform_interface
description: A common platform interface for the update_available plugin.
version: 4.1.1
repository: https://github.com/mateusfccp/update_available/tree/master/update_available_platform_interface

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: '>=1.9.1 <2.0.0'
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0
