name: update_available_platform_interface
description: A common platform interface for the update_available plugin.
version: 3.1.0
repository: https://github.com/mateusfccp/update_available/tree/master/update_available_platform_interface

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_lints: ^2.0.0
