name: update_available
description: Know if there's any update for your Flutter app, based on published versions.
version: 3.0.0-dev.2
repository: https://github.com/mateusfccp/update_available/tree/master/update_available

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  update_available_android: ^3.0.0-dev.2
  update_available_ios: ^3.0.0-dev.3
  update_available_platform_interface: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        default_package: update_available_android
      ios:
        default_package: update_available_ios
