name: update_available
description: Know if there's any update for your Flutter app, based on published versions.
version: 2.3.0
repository: https://github.com/mateusfccp/update_available/tree/master/update_available

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  update_available_android: ^2.3.0
  update_available_ios: ^2.3.0
  update_available_platform_interface: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: update_available_android
      ios:
        default_package: update_available_ios
