name: update_available_ios
description: iOS platform implementation of update_available
version: 3.1.0+1
repository: https://github.com/mateusfccp/update_available/tree/master/update_available_ios

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: '>=1.9.1 <2.0.0'
  package_info_plus: '>=4.0.2 <10.0.0'
  pub_semver: ^2.1.4
  update_available_platform_interface: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.7

flutter:
  plugin:
    implements: update_available
    platforms:
      ios:
        dartPluginClass: UpdateAvailableIosPlugin
