name: update_available_ios
description: iOS platform implementation of update_available
version: 3.0.1
repository: https://github.com/mateusfccp/update_available/tree/master/update_available_ios

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  package_info_plus: ">=4.0.2 <6.0.0"
  pub_semver: ^2.1.4
  update_available_platform_interface: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  test: ^1.24.0

flutter:
  plugin:
    implements: update_available
    platforms:
      ios:
        dartPluginClass: UpdateAvailableIosPlugin
