name: update_available_ios
description: iOS platform implementation of update_available
version: 2.0.0
repository: https://github.com/mateusfccp/update_available/tree/master/update_available_ios

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  meta: ^1.3.0
  package_info: ^2.0.0
  update_available_platform_interface: ^2.0.0
  pub_semver: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
