name: update_available_example
description: Example for update_available package.
version: 1.1.0
repository: https://github.com/mateusfccp/update_available/tree/master/update_available
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  update_available:
    path: ..

dev_dependencies:
  flutter_lints: ^1.0.4
