name: update_available_example
description: Example for update_available package.
version: 1.1.0
repository: https://github.com/mateusfccp/update_available/tree/master/update_available
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  update_available:
    path: ..

dev_dependencies:
  flutter_lints: ^2.0.0

dependency_overrides:
  update_available_android:
    path: ../../update_available_android
  update_available_ios:
    path: ../../update_available_ios
  update_available_platform_interface:
    path: ../../update_available_platform_interface
